# Generated by Django 5.0.3 on 2024-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_default=None, default=None, max_length=256, null=True)),
                ('config_type', models.CharField(choices=[('member_free', 'member_free'), ('member_standard', 'member_standard'), ('member_premium', 'member_premium'), ('award', 'award'), ('activity', 'activity')], db_default=None, default=None, max_length=128, null=True)),
                ('sub_type', models.CharField(choices=[('month', 'month'), ('quarter', 'quarter'), ('year', 'year'), ('subscribed_bot', 'subscribed_bot'), ('invite_register', 'invite_register'), ('monthly', 'monthly'), ('discount', 'discount')], db_default=None, default=None, max_length=128, null=True)),
                ('value', models.JSONField(db_default=None, default=None, null=True)),
                ('order', models.IntegerField(db_default=0, default=0)),
                ('updated_by', models.CharField(db_default=None, default=None, max_length=36, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'global config',
                'db_table': 'global_config',
                'unique_together': {('config_type', 'sub_type')},
            },
        ),
    ]
