# Generated by Django 5.0.3 on 2024-03-12 09:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('doc_id', models.BigIntegerField(null=True)),
                ('collection_type', models.CharField(
                    blank=True, db_default='personal', default='personal', max_length=32, null=True)),
                ('title', models.CharField(
                    blank=True, db_default=None, db_index=True, default=None, max_length=200, null=True)),
                ('abstract', models.TextField(blank=True, db_default=None, null=True)),
                ('authors', models.JSONField(null=True)),
                ('doi', models.CharField(blank=True, db_default=None, default=None, max_length=128, null=True)),
                ('categories', models.JSONField(null=True)),
                ('page_num', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('pub_date', models.DateField(null=True)),
                ('pub_type', models.CharField(blank=True, db_default=None, default=None, max_length=32, null=True)),
                ('journal', models.CharField(blank=True, db_default=None, default=None, max_length=128, null=True)),
                ('conference', models.CharField(blank=True, db_default=None, default=None, max_length=256, null=True)),
                ('keywords', models.JSONField(null=True)),
                ('is_open_access', models.BooleanField(db_default=False, default=False, null=True)),
                ('citation_count', models.IntegerField(null=True)),
                ('reference_count', models.IntegerField(null=True)),
                ('citations', models.JSONField(null=True)),
                ('state', models.CharField(
                    blank=True, db_default='completed', default='completed', max_length=32, null=True)),
                ('object_path', models.CharField(blank=True, max_length=256, null=True)),
                ('source_url', models.CharField(blank=True, max_length=256, null=True)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('collection', models.ForeignKey(
                    db_column='collection_id', db_constraint=False, null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING, to='collection.collection')),
                ('user', models.ForeignKey(
                    db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentLibrary',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('document', models.ForeignKey(
                    db_column='document_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='doc_lib', to='document.document')),
                ('user', models.ForeignKey(
                    db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document_library',
                'db_table': 'document_library',
            },
        ),
        migrations.CreateModel(
            name='IngestDocument',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('task_id', models.CharField(blank=True, max_length=36, null=True)),
                ('task_status', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('doc_id', models.BigIntegerField(db_default=None, default=None, null=True)),
                ('collection_type', models.CharField(blank=True, max_length=32, null=True)),
                ('collection_id', models.CharField(blank=True, max_length=36, null=True)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(
                    db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
