# Generated by Django 5.0.3 on 2024-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ref_collection_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ref_doc_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='venue',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=128, null=True),
        ),
    ]
