# Generated by Django 5.0.3 on 2024-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_ref_collection_id_document_ref_doc_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_open_access',
        ),
        migrations.AddField(
            model_name='document',
            name='full_text_accessible',
            field=models.BooleanField(db_default=None, default=None, null=True),
        ),
    ]
