# Generated by Django 5.0.3 on 2024-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_documentlibrary_error_documentlibrary_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='del_flag',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
