# Generated by Django 5.0.3 on 2024-04-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_document_del_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='page_num',
            new_name='pages',
        ),
    ]
