# Generated by Django 5.0.3 on 2024-04-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_bot_author'),
        ('collection', '0004_collectiondocument_full_text_accessible'),
        ('document', '0008_rename_page_num_document_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlibraryfolder',
            name='bot',
            field=models.ForeignKey(db_column='bot_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.bot'),
        ),
        migrations.AddField(
            model_name='documentlibraryfolder',
            name='collection',
            field=models.ForeignKey(db_column='collection_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='document',
            name='state',
            field=models.CharField(blank=True, db_default='undone', default='undone', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='IngestDocument',
        ),
    ]
