# Generated by Django 5.0.3 on 2024-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collectiondocument_doc_collection_id_and_more'),
        ('document', '0009_documentlibraryfolder_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlibrary',
            name='collection_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='documentlibrary',
            name='doc_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentlibrary',
            name='task_type',
            field=models.CharField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('collection', 'doc_id')},
        ),
        migrations.AlterIndexTogether(
            name='documentlibrary',
            index_together={('collection_id', 'doc_id')},
        ),
    ]
