# Generated by Django 5.0.3 on 2024-05-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_documentlibrary_collection_id_documentlibrary_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doi',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='journal',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='venue',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=256, null=True),
        ),
    ]
