# Generated by Django 5.0.3 on 2024-06-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_document_doi_alter_document_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author_names_ids',
            field=models.JSONField(null=True),
        ),
    ]
