# Generated by Django 5.0.3 on 2024-03-12 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_default=None, default=None, max_length=128, null=True)),
                ('bot_id', models.CharField(blank=True, db_default=None, default=None, max_length=36, null=True)),
                ('type', models.CharField(blank=True, db_default='personal', default='personal', max_length=32, null=True)),
                ('total', models.IntegerField(db_default=0, default=0)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collection',
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='CollectionDocument',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('collection', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_doc', to='collection.collection')),
            ],
            options={
                'verbose_name': 'collection_document',
                'db_table': 'collection_document',
            },
        ),
    ]
