# Generated by Django 5.0.3 on 2024-03-12 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondocument',
            name='document',
            field=models.ForeignKey(
                db_column='document_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                to='document.document'),
        ),
    ]
