# Generated by Django 5.0.3 on 2024-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='total',
            new_name='total_personal',
        ),
        migrations.AddField(
            model_name='collection',
            name='total_public',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=255, null=True),
        ),
    ]
