# Generated by Django 5.0.3 on 2024-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_rename_total_collection_total_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondocument',
            name='full_text_accessible',
            field=models.BooleanField(db_default=None, default=None, null=True),
        ),
    ]
