# Generated by Django 5.0.3 on 2024-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collectiondocument_full_text_accessible'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondocument',
            name='doc_collection_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='collectiondocument',
            name='doc_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterIndexTogether(
            name='collectiondocument',
            index_together={('doc_collection_id', 'doc_id')},
        ),
    ]
