# Generated by Django 5.0.3 on 2024-03-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prompt',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='question',
            name='docs',
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_id',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='paper_ids',
            field=models.JSONField(blank=True, db_default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='public_collection_ids',
            field=models.JSONField(blank=True, db_default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='stream',
            field=models.JSONField(blank=True, db_default=None, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(blank=True, choices=[('bot', 'bot'), ('doc', 'doc'), ('docs', 'docs'), ('doc_lib', 'doc_lib'), ('collection', 'collection'), ('collections', 'collections'), ('mix', 'mix'), ('simple', 'simple')], db_default=None, default=None, max_length=32, null=True),
        ),
    ]
