# Generated by Django 5.0.3 on 2024-03-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_prompt_question_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_tokens',
            field=models.IntegerField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='output_tokens',
            field=models.IntegerField(db_default=None, default=None, null=True),
        ),
    ]
