# Generated by Django 5.0.3 on 2024-03-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_question_input_tokens_question_output_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_named',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
