# Generated by Django 5.0.3 on 2024-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_is_named'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='docs',
            new_name='documents',
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_id',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='collections',
            field=models.JSONField(null=True),
        ),
    ]
