# Generated by Django 5.0.3 on 2024-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_docs_conversation_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_stop',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
