# Generated by Django 5.0.3 on 2024-05-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_question_is_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model',
            field=models.CharField(blank=True, db_default='gpt-3.5-turbo', default='gpt-3.5-turbo', max_length=64, null=True),
        ),
    ]
