# Generated by Django 5.0.3 on 2024-05-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_question_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='source',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=1024, null=True),
        ),
    ]
