# Generated by Django 5.0.3 on 2024-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_api',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
