# Generated by Django 5.0.3 on 2024-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_question_source_alter_question_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='model',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=64, null=True),
        ),
    ]
