# Generated by Django 5.0.3 on 2024-05-15 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenapiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('api_key', models.CharField(max_length=128, unique=True)),
                ('api_key_show', models.CharField(max_length=128, unique=True)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'openapi_key',
                'db_table': 'openapi_key',
            },
        ),
        migrations.CreateModel(
            name='OpenapiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, db_default='', default='', max_length=256)),
                ('api', models.IntegerField(choices=[(1, 'Search'), (2, 'Conversation'), (3, 'Upload Paper'), (4, 'List Bots'), (5, 'List My Bots'), (6, 'List My Doc Libs')], db_index=True)),
                ('obj_id1', models.CharField(db_default=None, db_index=True, default=None, max_length=40, null=True)),
                ('obj_id2', models.CharField(db_default=None, db_index=True, default=None, max_length=40, null=True)),
                ('obj_id3', models.BigIntegerField(db_default=None, db_index=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Success'), (2, 'Failed')], db_default=0, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('openapi_key', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='openapi.openapikey')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'openapi_log',
                'db_table': 'openapi_log',
            },
        ),
        migrations.CreateModel(
            name='OpenapiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, db_default='', default='', max_length=256)),
                ('api', models.IntegerField(choices=[(1, 'Search'), (2, 'Conversation'), (3, 'Upload Paper'), (4, 'List Bots'), (5, 'List My Bots'), (6, 'List My Doc Libs')], db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('total', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('openapi_key', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='openapi.openapikey')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'openapi_usage',
                'db_table': 'openapi_usage',
                'unique_together': {('user', 'openapi_key', 'model', 'api', 'date')},
            },
        ),
    ]
