# Generated by Django 5.0.3 on 2024-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openapikey',
            name='api_key_show',
            field=models.CharField(max_length=128),
        ),
    ]
