# Generated by Django 5.0.3 on 2024-07-08 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openapi', '0003_alter_openapilog_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_start_date', models.DateField(null=True)),
                ('standard_end_date', models.DateField(null=True)),
                ('standard_total_days', models.IntegerField(null=True)),
                ('premium_start_date', models.DateField(null=True)),
                ('premium_end_date', models.DateField(null=True)),
                ('premium_total_days', models.IntegerField(null=True)),
                ('is_vip', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'member',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='MemberUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_default=None, default=None, max_length=256, null=True)),
                ('type', models.IntegerField(choices=[(2, 'Conversation'), (3, 'Upload Paper')], db_index=True)),
                ('obj_id1', models.CharField(db_default=None, db_index=True, default=None, max_length=40, null=True)),
                ('obj_id2', models.CharField(db_default=None, db_index=True, default=None, max_length=40, null=True)),
                ('obj_id3', models.BigIntegerField(db_default=None, db_index=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Success'), (2, 'Failed')], db_default=0, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('openapi_key', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='openapi.openapikey')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(db_default=0, default=0)),
                ('appid', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('mchid', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('out_trade_no', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('transaction_id', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('trade_type', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('trade_state', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('NOTPAY', 'NOTPAY'), ('CLOSED', 'CLOSED'), ('REFUND', 'REFUND')], db_default=None, default=None, max_length=128, null=True)),
                ('trade_state_desc', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('bank_type', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('attach', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('success_time', models.DateTimeField(db_default=None, default=None, null=True)),
                ('payer', models.JSONField(db_default=None, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pay',
                'db_table': 'pay',
            },
        ),
        migrations.CreateModel(
            name='TokensHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=128)),
                ('title', models.CharField(db_default=None, default=None, max_length=256, null=True)),
                ('amount', models.IntegerField(db_default=0, default=0)),
                ('pay_amount', models.IntegerField(db_default=0, default=0)),
                ('used', models.IntegerField(db_default=0, default=0)),
                ('type', models.CharField(choices=[
                    ('wxpay', 'wxpay'),
                    ('exchange_standard_30', 'exchange_standard_30'), ('exchange_standard_90', 'exchange_standard_90'), ('exchange_standard_360', 'exchange_standard_360'),
                    ('exchange_premium_30', 'exchange_premium_30'), ('exchange_premium_90', 'exchange_premium_90'), ('exchange_premium_360', 'exchange_premium_360'),
                    ('subscribed_bot', 'subscribed_bot'), ('invite_register', 'invite_register'),
                    ('register_award', 'register_award'), ('monthly_award', 'monthly_award'), ('expiration', 'expiration')
                ], db_default=None, default=None, max_length=128, null=True)),
                ('out_trade_no', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('start_date', models.DateField(db_default=None, default=None, null=True)),
                ('end_date', models.DateField(db_default=None, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'delete'), (1, 'has_balance'), (2, 'completed'), (3, 'in_progress'), (4, 'freezing'), (5, 'expired')], db_default=None, default=None, null=True)),
                ('give_user', models.ForeignKey(db_column='give_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='give_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tokens history',
                'db_table': 'tokens_history',
            },
        ),
    ]
