# Generated by Django 5.0.3 on 2024-07-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_pay_code_url_pay_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberusagelog',
            options={'verbose_name': 'member usage log'},
        ),
        migrations.AlterModelTable(
            name='memberusagelog',
            table='member_usage_log',
        ),
    ]
