# Generated by Django 5.0.3 on 2024-07-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_alter_memberusagelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
