# Generated by Django 5.0.3 on 2024-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0004_member_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='premium_total_days',
            new_name='premium_remain_days',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='standard_total_days',
            new_name='standard_remain_days',
        ),
        migrations.AlterField(
            model_name='tokenshistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'delete'), (2, 'completed'), (3, 'in_progress'), (4, 'freezing')], db_default=None, default=None, null=True),
        ),
    ]
