# Generated by Django 5.0.3 on 2024-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0005_rename_premium_total_days_member_premium_remain_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenshistory',
            name='freezing_date',
            field=models.DateField(db_default=None, default=None, null=True),
        ),
    ]
