# Generated by Django 5.0.3 on 2024-07-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0006_tokenshistory_freezing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='code_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='memberusagelog',
            name='type',
            field=models.IntegerField(choices=[(2, 'Chat'), (3, 'Embedding')], db_index=True),
        ),
        migrations.AlterField(
            model_name='tokenshistory',
            name='type',
            field=models.CharField(choices=[('wxpay', 'wxpay'), ('exchange_standard_30', 'exchange_standard_30'), ('exchange_standard_90', 'exchange_standard_90'), ('exchange_standard_360', 'exchange_standard_360'), ('exchange_premium_30', 'exchange_premium_30'), ('exchange_premium_90', 'exchange_premium_90'), ('exchange_premium_360', 'exchange_premium_360'), ('subscribed_bot', 'subscribed_bot'), ('invite_register', 'invite_register'), ('duration_award', 'duration_award'), ('new_user_award', 'new_user_award'), ('expiration', 'expiration')], db_default=None, default=None, max_length=128, null=True),
        ),
    ]
