# Generated by Django 5.0.3 on 2024-03-12 09:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSubscribe',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'bot_subscribe',
                'db_table': 'bot_subscribe',
            },
        ),
        migrations.CreateModel(
            name='HotBot',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField()),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'hot_bot',
                'db_table': 'hot_bot',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('author', models.CharField(blank=True, db_default=None, default=None, max_length=64, null=True)),
                ('title', models.CharField(blank=True, db_default=None, default=None, max_length=200, null=True)),
                ('prompt', models.JSONField(blank=True, db_default=None, null=True)),
                ('description', models.TextField(blank=True, db_default=None, null=True)),
                ('questions', models.JSONField(db_default=None, default=None, null=True)),
                ('llm', models.JSONField(db_default=None, default=None, null=True)),
                ('tools', models.JSONField(db_default=None, default=None, null=True)),
                ('cover_url', models.CharField(blank=True, db_default=None, default=None, max_length=256, null=True)),
                ('type', models.CharField(
                    blank=True, choices=[('personal', 'personal'), ('public', 'public')], db_default='personal',
                    default='personal', max_length=32, null=True)),
                ('pub_date', models.DateField(null=True)),
                ('extension', models.JSONField(null=True)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(
                    db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bot',
                'db_table': 'bot',
            },
        ),
        migrations.CreateModel(
            name='BotCollection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('collection_type', models.CharField(
                    blank=True, choices=[('personal', 'personal'), ('public', 'public')], db_default='personal',
                    default='personal', max_length=32, null=True)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bot', models.ForeignKey(
                    db_column='bot_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='bot_collection', to='bot.bot')),
            ],
            options={
                'verbose_name': 'bot_collection',
                'db_table': 'bot_collection',
            },
        ),
    ]
