# Generated by Django 5.0.3 on 2024-03-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botcollection',
            name='collection',
            field=models.ForeignKey(
                db_column='collection_id', db_constraint=False, null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, related_name='bot_collection',
                to='collection.collection'),
        ),
        migrations.AddField(
            model_name='botsubscribe',
            name='bot',
            field=models.ForeignKey(
                db_column='bot_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='bot_subscribe', to='bot.bot'),
        ),
        migrations.AddField(
            model_name='botsubscribe',
            name='user',
            field=models.ForeignKey(
                db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotbot',
            name='bot',
            field=models.ForeignKey(
                db_column='bot_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                to='bot.bot'),
        ),
    ]
