# Generated by Django 5.0.3 on 2024-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='author',
            field=models.CharField(blank=True, db_default=None, default=None, max_length=128, null=True),
        ),
    ]
