# Generated by Django 5.0.3 on 2024-05-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_bot_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[('personal', 'personal'), ('in_progress', 'in_progress'), ('public', 'public')],
                db_default='personal', default='personal', max_length=32, null=True
            ),
        ),
    ]
