# Generated by Django 5.0.3 on 2024-05-20 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_bot_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTools',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True)),
                ('url', models.CharField(blank=True, null=True)),
                ('openapi_json_path', models.CharField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('basic', 'basic'), ('bearer', 'bearer'), ('api_key', 'api_key')], db_default=None, default=None, null=True)),
                ('username_password_base64', models.CharField(blank=True, null=True)),
                ('token', models.CharField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, null=True)),
                ('custom_header', models.CharField(blank=True, null=True)),
                ('endpoints', models.JSONField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('checked', models.BooleanField(db_default=False, default=False)),
                ('del_flag', models.BooleanField(db_default=False, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bot', models.ForeignKey(db_column='bot_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bot_tools', to='bot.bot')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bot_tools',
                'db_table': 'bot_tools',
            },
        ),
    ]
