# Generated by Django 5.0.3 on 2024-06-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_bottools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.CharField(blank=True, choices=[('personal', 'personal'), ('in_progress', 'in_progress'), ('public', 'public'), ('share', 'share')], db_default='personal', default='personal', max_length=32, null=True),
        ),
    ]
