# Generated by Django 5.0.3 on 2024-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_bot_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='advance_share',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
