# Generated by Django 5.0.2 on 2024-02-29 06:05

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(db_default=None, default=None, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(db_default=None, default=None, max_length=14, null=True, unique=True)),
                ('nickname', models.CharField(db_default=None, default=None, max_length=128, null=True)),
                ('avatar', models.CharField(db_default=None, default=None, max_length=256, null=True)),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='last name')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='password')),
                ('is_superuser', models.BooleanField(db_default=False, default=False, verbose_name='superuser status')),
                ('is_staff', models.BooleanField(db_default=False, default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(db_default=True, default=True, verbose_name='active')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('description', models.TextField(db_default=None, null=True)),
                ('groups', models.ManyToManyField(
                    blank=True,
                    help_text='The groups this user belongs to. A user will get all permissions granted '
                              'to each of their groups.',
                    related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')
                 ),
                ('user_permissions', models.ManyToManyField(
                    blank=True, help_text='Specific permissions for this user.', related_name='user_set',
                    related_query_name='user', to='auth.permission', verbose_name='user permissions')
                 ),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'my_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
