# Generated by Django 5.0.3 on 2024-05-08 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperationLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(db_index=True, max_length=32)),
                ('obj_id1', models.CharField(db_default=None, db_index=True, default=None, max_length=40, null=True)),
                ('obj_id2', models.CharField(db_default=None, db_index=True, default=None, max_length=40, null=True)),
                ('obj_id3', models.BigIntegerField(db_default=None, db_index=True, default=None, null=True)),
                ('operation_content', models.TextField(db_default=None, default=None, null=True)),
                ('result', models.JSONField(db_default=None, default=None, null=True)),
                ('source', models.CharField(db_default=None, default=None, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_operation_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user operation log',
                'db_table': 'user_operation_log',
            },
        ),
    ]
