# Generated by Django 5.0.3 on 2024-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_myuser_email_alter_myuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='register_source',
            field=models.JSONField(db_default=None, default=None, max_length=64, null=True),
        ),
    ]
