# Generated by Django 5.0.3 on 2024-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myuser_register_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(db_default=None, default=None, max_length=4096, null=True),
        ),
    ]
